# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheseaMeanTemperature',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."tmean_30s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemMex',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
            options={
                'db_table': 'demmex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DemMexLow',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
            options={
                'db_table': 'demmex120',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaxTemperature',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."tmax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeanTemperature',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."tavg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MinTemperature',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."tmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."prec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolarRadiation',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."srad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
            options={
                'db_table': 'testviirs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaporPressure',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."vapr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('band', models.TextField(db_column=b'filename')),
            ],
            options={
                'db_table': 'bioclim"."wind',
                'managed': False,
            },
        ),
    ]
