# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 21:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETOPO1',
            fields=[
                ('id', models.AutoField(db_column=b'rid', primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
            options={
                'db_table': 'etopo1_ice_c_geotiff',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='maxtemperature',
            table='bioclim"."world-tmax',
        ),
        migrations.AlterModelTable(
            name='precipitation',
            table='bioclim"."world-prec',
        ),
        migrations.AlterModelTable(
            name='solarradiation',
            table='bioclim"."world-srad',
        ),
    ]
