version: '3'

#networks:
#  default:
#   external:
#    name: 'biospytial_network_local'

#docker network create \
#  --driver=overlay \
#  --subnet=10.0.9.0/24 \
#  --attachable=true \
#  biospytial_network_2


      
      
services:

 ## Biospytial client
 client:
  ports:
   - '8888:8888'
   - '8000:8000'
   - '2323:2323'
  volumes:
   - '/Users/juan/Biospytial/gbif_data/RawDataCSV:/RawDataCSV'
   - '/Users/juan/Biospytial/outputs:/outputs'
   - '/Users/juan/git_projects/biospytial:/apps'
   - '/tmp/.X11-unix:/tmp/.X11-unix'
  deploy:
   mode: global
   resources:
    limits:
     memory: 25g
   #replicas: 2
   update_config:
    parallelism: 1
    delay: 10s
  links:
   - postgis
   - neo4j
  depends_on:
   - postgis
   - neo4j
   - redis
  environment:
    #DISPLAY: '${DISPLAY}'
   - DISPLAY="host.docker.internal:0"
    #image: molgor/biospytial
  image: molgor/biospytial:latest-beta
  #image: molgor/biospytial:dev-updatedlibs-latest
  # For interactive mode
  stdin_open: true
  tty: true
  entrypoint: /root/entrypoint.sh
  #entrypoint: /bin/bash
  

### Postgis container
 postgis:
  ports:
   - 5432:5432
  deploy:
   replicas: 1 
   update_config:
    parallelism: 1
    delay: 10s
  volumes:
   - '/Users/juan/DataVolumesBank/DataVolumes/postgis-container/world_bioclim/postgis:/DataVolumes'
  image: molgor/postgis_biospytial
  entrypoint: /bin/sh -c "/root/startPostgres"
 
### The Neo4j thing
 neo4j:
  environment:
   NEO4J_AUTH: none
  ports:
   - 7474:7474
   - 7687:7687
   - 1337:1337
  deploy:
   replicas: 1
   update_config:
    parallelism: 1
    delay: 10s
  volumes:
   - '/Users/juan/DataVolumesBank/DataVolumes/neo4j-container/data:/data'
   - '/Users/juan/DataVolumesBank/DataVolumes/neo4j-container/logs:/logs'
  image: molgor/neo4j_biospytial:3.1.3   
  
  
### The Redis message and key:value store
 redis:
  ports:
   - 6379:6379
  volumes:
   - '/Users/juan/DataVolumesBank/DataVolumes/redis:/data'
  image: redis
  



  
