name: biospytial
dependencies:
- cairo=1.12.18=6
- curl=7.43.0=1
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- django=1.8.4=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- gdal=2.0.0=py27_1
- geos=3.4.2=0
- hdf4=4.2.11=0
- hdf5=1.8.15.1=2
- ipython=4.0.1=py27_0
- ipython_genutils=0.1.0=py27_0
- jpeg=8d=0
- kealib=1.4.5=0
- krb5=1.13.2=0
- libgdal=2.0.0=2
- libgfortran=1.0=0
- libnetcdf=4.3.3.1=1
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.0=np110py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=3
- openssl=1.0.1k=1
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- pixman=0.32.6=0
- proj4=4.9.1=0
- py2cairo=1.10.0=py27_2
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pyside=1.2.1=py27_1
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=19.1.1=py27_0
- shiboken=1.2.1=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- xerces-c=3.1.2=0
- zlib=1.2.8=0
- pip:
  - django-extensions==1.6.1
  - django-pdb==0.4.2
  - ete2==2.3.10
  - ipdb==0.8.1
  - ipython-genutils==0.1.0
  - psycopg2==2.6.1

