#!/usr/bin/env python
#-*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals
import os
from django.contrib.gis.utils import LayerMapping
from .models import TerrEcoregions
from biospytial import settings
"""
Functions for exporting shapefiles into the Postgis Database.
"""


__author__ = "Juan Escamilla Mólgora"
__copyright__ = "Copyright 2018, JEM"
__license__ = "GPL"
__mantainer__ = "Juan"
__email__ ="molgor@gmail.com"

## Generated by ogrinspect
terrecoregions_mapping = {
    'eco_id_u' : 'ECO_ID_U',
    'eco_code' : 'ECO_CODE',
    'eco_name' : 'ECO_NAME',
    'eco_num' : 'ECO_NUM',
    'ecode_name' : 'ECODE_NAME',
    'cls_code' : 'CLS_CODE',
    'eco_notes' : 'ECO_NOTES',
    'wwf_realm' : 'WWF_REALM',
    'wwf_realm2' : 'WWF_REALM2',
    'wwf_mhtnum' : 'WWF_MHTNUM',
    'wwf_mhtnam' : 'WWF_MHTNAM',
    'realmmht' : 'RealmMHT',
    'er_update' : 'ER_UPDATE',
    'er_date_u' : 'ER_DATE_U',
    'er_ration' : 'ER_RATION',
    'sourcedata' : 'SOURCEDATA',
    'geom' : 'MULTIPOLYGON',
}

file_shp = os.path.abspath(
    os.path.join(settings.PATH_RAWDATASOURCES, 'terr-ecoregions-TNC', 'tnc_terr_ecoregions.shp'),
)

def run(verbose=True):
    lm = LayerMapping(
        TerrEcoregions, file_shp, terrecoregions_mapping,
        transform=False,       
    )
    lm.save(verbose=True,step=100)

