version: '2'

networks:
  default:
   external:
    name: 'biospytial_network_local'

services:
 postgis:
  ports:
   - 5432:5432
  volumes:
   - '/home/juan/DataVolumesBank/postgis:/DataVolumes'
   - '/mnt/data1:/mnt/data1'
  image: molgor/postgis_biospytial
  entrypoint: /bin/sh -c "/root/startPostgres"