# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grid',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'grid025mex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mesh',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."braz_grid2048a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MexMesh',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('gid', models.IntegerField(db_column=b'id')),
                ('xmin', models.FloatField(db_column=b'__xmin')),
                ('xmax', models.FloatField(db_column=b'__xmax')),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('cell', django.contrib.gis.db.models.fields.MultiPolygonField(db_column=b'geom', srid=4326)),
            ],
            options={
                'db_table': 'grid4km-mex',
                'managed': False,
            },
        ),
    ]
