# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 21:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh1',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
                'db_table': 'mesh"."mexico_grid1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh10',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid512',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh2',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh3',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh4',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh5',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid16',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh6',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid32',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh7',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid64',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh8',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid128',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesh9',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('cell', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mesh"."mexico_grid256',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='mexmesh',
            table='mesh"."mex4km',
        ),
    ]
