# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gbif', '0015_auto_20160407_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence_CSV_Verbatim',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, db_column=b'id_gbif')),
                ('dataset_id', models.TextField(null=True, blank=True)),
                ('institution_code', models.TextField(null=True, blank=True)),
                ('collection_code', models.TextField(null=True, blank=True)),
                ('catalog_number', models.TextField(null=True, blank=True)),
                ('basis_of_record', models.TextField(null=True, blank=True)),
                ('scientific_name', models.TextField(db_index=True, null=True, blank=True)),
                ('scientific_name_author', models.TextField(null=True, blank=True)),
                ('taxon_id', models.IntegerField(null=True, blank=True)),
                ('kingdom', models.TextField(db_index=True, null=True, blank=True)),
                ('phylum', models.TextField(db_index=True, null=True, blank=True)),
                ('_class', models.TextField(db_index=True, null=True, blank=True)),
                ('_order', models.TextField(db_index=True, null=True, blank=True)),
                ('family', models.TextField(db_index=True, null=True, blank=True)),
                ('genus', models.TextField(db_index=True, null=True, blank=True)),
                ('specific_epithet', models.TextField(db_index=True, null=True, blank=True)),
                ('kingdom_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('phylum_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('class_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('order_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('family_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('genus_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('species_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('country_code', models.TextField(max_length=7, null=True, blank=True)),
                ('latitude', models.FloatField(db_index=True, null=True, blank=True)),
                ('longitude', models.FloatField(db_index=True, null=True, blank=True)),
                ('year', models.IntegerField(db_index=True, null=True, blank=True)),
                ('month', models.IntegerField(db_index=True, null=True, blank=True)),
                ('event_date', models.DateTimeField(db_index=True, null=True, blank=True)),
                ('elevation_in_meters', models.TextField(null=True, blank=True)),
                ('depth_in_meters', models.TextField(null=True, blank=True)),
                ('verbatim_scientific_name', models.TextField(null=True, blank=True)),
                ('taxon_rank', models.TextField(null=True, blank=True)),
                ('verbatim_kingdom', models.TextField(null=True, blank=True)),
                ('verbatim_phylum', models.TextField(null=True, blank=True)),
                ('verbatim_class', models.TextField(null=True, blank=True)),
                ('verbatim_order', models.TextField(null=True, blank=True)),
                ('verbatim_family', models.TextField(null=True, blank=True)),
                ('verbatim_genus', models.TextField(null=True, blank=True)),
                ('verbatim_specific_epithet', models.TextField(null=True, blank=True)),
                ('verbatim_infraspecific_epithet', models.TextField(null=True, blank=True)),
                ('verbatim_latitude', models.TextField(null=True, blank=True)),
                ('verbatim_longitude', models.TextField(null=True, blank=True)),
                ('coordinate_precision', models.TextField(null=True, blank=True)),
                ('maximum_elevation_in_meters', models.TextField(null=True, blank=True)),
                ('minimum_elevation_in_meters', models.TextField(null=True, blank=True)),
                ('elevation_precision', models.TextField(null=True, blank=True)),
                ('minimum_depth_in_meters', models.TextField(null=True, blank=True)),
                ('maximum_depth_in_meters', models.TextField(null=True, blank=True)),
                ('depth_precision', models.TextField(null=True, blank=True)),
                ('continent_ocean', models.TextField(null=True, blank=True)),
                ('state_province', models.TextField(null=True, blank=True)),
                ('county', models.TextField(null=True, blank=True)),
                ('country', models.TextField(null=True, blank=True)),
                ('recorded_by', models.TextField(null=True, blank=True)),
                ('locality', models.TextField(null=True, blank=True)),
                ('verbatim_year', models.TextField(null=True, blank=True)),
                ('verbatim_month', models.TextField(null=True, blank=True)),
                ('day', models.IntegerField(null=True, blank=True)),
                ('verbatim_basis_of_record', models.TextField(null=True, blank=True)),
                ('identified_by', models.TextField(null=True, blank=True)),
                ('date_identified', models.TextField(null=True, blank=True)),
                ('created', models.TextField(null=True, blank=True)),
                ('modified', models.TextField(null=True, blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
            ],
        ),
    ]
