version: '2'

networks:
  default:
   external:
    name: 'biospytial_network_local'

services:

 ## Biospytial client
 client:
  ports:
   - '8888:8888'
  volumes:
   - '/mnt/data1/RawDataCSV:/RawDataCSV'
   - '/mnt/data1/git-projects/biospytial:/apps'
   - '/mnt/data1:/mnt/data1'
   - '/tmp/.X11-unix:/tmp/.X11-unix'
  
  #links:
  # - postgis
  # - neo4j
  #depends_on:
  # - postgis
  # - neo4j
  environment:
    DISPLAY: unix$DISPLAY
  image: molgor/biospytial
  # For interactive mode
  stdin_open: true
  tty: true
  entrypoint: /bin/bash

 

   