version: '3'
     
services:
 ## Biospytial client
 client:
  #env_file:
  # - .env
  ports:
   - '8888:8888'
   - '8000:8000'
   - '2323:2323'
  volumes:
   - '${GENERAL_PATH}${INPUT_PATH}:/RawDataCSV'
   - '${GENERAL_PATH}${OUTPUT_PATH}:/outputs'
   - '${GENERAL_PATH}${BIOSPYTIAL_PATH}:/apps'
   - '${GENERAL_PATH}:/mnt/data1'
   - '/tmp/.X11-unix:/tmp/.X11-unix'
   - '/tmp:/tmp'
   - '${HOME}/.Xauthority:/root/.Xauthority'

  deploy:
   placement:
    constraints:
     - node.role == manager
#   replicas: 2   
#   mode: global
   resources:
    limits:
     memory: 25g
   #replicas: 2
   update_config:
    parallelism: 1
    delay: 10s
  links:
   - postgis
   - neo4j
  depends_on:
   - postgis
   - neo4j
   - redis
  environment:
   - DISPLAY="host.docker.internal:0"
    #DISPLAY: 'unix:0'
   - LANG="C.UTF-8"
  shm_size: 1024M
  #  image: molgor/biospytial
  image: molgor/biospytial:latest-beta
  # For interactive mode
  stdin_open: true
  tty: true
  entrypoint: /root/entrypoint.sh
  #entrypoint: /bin/bash
  #entrypoint: /bin/sh -c "tail -f /dev/null"

### Postgis container
 postgis:
  #env_file:
  # - .env
  ports:
   - 5432:5432
  deploy:
   #replicas: 2
   placement:
    constraints:
     - node.role == manager
   update_config:
    parallelism: 1
    delay: 10s
  volumes:
   - '${BIOSPYTIAL_DATAPATH}${POSTGIS_DATAPATH}:/DataVolumes'
   - '${GENERAL_PATH}:/mnt/data1'
  image: molgor/postgis_biospytial
  entrypoint: /bin/sh -c "/root/startPostgres"
  # Maintenance mode
  # Uncomment and run with docker exec -it biospytial_postgis_1 bash
  #entrypoint: /bin/sh -c "tail -f /dev/null"
### The Neo4j service
 neo4j:
  env_file:
   - .env
  environment:
   NEO4J_AUTH: none
  ports:
   - 7474:7474
   - 7687:7687
   - 1337:1337
  deploy:
   #replicas: 2   
   placement:
    constraints:
     - node.role == manager
   update_config:
    parallelism: 1
    delay: 10s
  volumes:
   - '${BIOSPYTIAL_DATAPATH}${GRAPH_DATABASE}/data:/data'
   - '${BIOSPYTIAL_DATAPATH}${GRAPH_DATABASE}/logs:/logs'
  image: molgor/neo4j_biospytial:3.1.3   
  
  
### The Redis message and key:value store
 redis:
  #env_file:
  # - .env
  ports:
   - 6379:6379
  deploy:
   placement:
    constraints:
     - node.role == manager
  volumes:
   - '${REDIS_DB}:/data'
  image: redis
  command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "biospytial."
      '
    ] 

  
