version: '2'

networks:
  default:
   external:
    name: 'biospytial_network_local'
 
services:
 neo4j:
  environment:
   NEO4J_AUTH: none
  ports:
   - 7474:7474
   - 7687:7687
   - 1337:1337
  volumes:
   - '/opt/DataVolumesFast/neo4j/data:/data'
   - '/opt/DataVolumesFast/neo4j/logs:/logs'
  image: molgor/neo4j_biospytial  