# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 21:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecoregion',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('cov', models.FloatField()),
                ('covid', models.FloatField()),
                ('tipo_zona', models.CharField(max_length=20)),
                ('num_zona', models.CharField(max_length=10)),
                ('nomzonecol', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'mex_ecoregions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InegiIV',
            fields=[
                ('id', models.AutoField(db_column=b'gid', primary_key=True, serialize=False)),
                ('covid', models.IntegerField(db_column=b'cov_id')),
                ('cov', models.IntegerField(db_column=b'cov_')),
                ('code', models.IntegerField(db_column=b'codigo')),
                ('name', models.CharField(db_column=b'descripcio', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'landuse-inegi5',
                'managed': False,
            },
        ),
    ]
