## The following requirements were added by pip freeze:
backports-abc==0.4
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
backports.weakref==1.0rc1
bleach==1.5.0
bulbs==0.3.29.post20140417
caniusepython3==6.0.0
click==6.7
click-plugins==1.0.3
cligj==0.4.0
coverage==4.4.2
cycler==0.10.0
dask==0.10.2
decorator==4.0.10
descartes==1.0.1
distlib==0.2.6
Django==1.10.5
django-adaptors==0.2.5
django-extensions==1.7.1
django-pdb==0.5.1
django-shell-plus==1.1.7
enum34==1.1.6
ete2==2.3.10
Fiona==1.7.9.post1
funcsigs==1.0.2
future==0.16.0
futures==3.1.1
GDAL==2.0.0
geopandas==0.3.0
GPflow==0.3.8
html5lib==0.9999999
httplib2==0.9.2
igraph==0.1.11
importlib==1.0.3
ipdb==0.8.1
ipykernel==4.1.1
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==4.1.0
Jinja2==2.8
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
lucene-querybuilder==0.2
lxml==3.8.0
Markdown==2.6.9
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.1
mock==2.0.0
mpmath==0.19
munch==2.2.0
nbconvert==4.1.0
nbformat==4.0.1
neo4django==0.1.8
neo4jrestclient==2.1.1
neomodel==2.0.2
networkx==1.11
notebook==4.0.6
numpy==1.11.2
nxpydot==0.1
omnijson==0.1.2
packaging==16.8
pandas==0.19.0
pandas-datareader==0.2.1
pandoc==1.0.0b2
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pbr==3.1.1
pexpect==4.2.1
pickleshare==0.7.4
PIL==1.1.7
Pillow==3.4.2
ply==3.9
prompt-toolkit==1.0.7
protobuf==3.4.0
psycopg2==2.6.2
ptyprocess==0.5.1
py2neo==3.1.1
pycairo==1.10.0
pydotplus==2.0.2
Pygments==2.1.3
pygraphviz==1.3.1
pyparsing==2.1.4
pyproj==1.9.5.1
PySide==1.2.1
python-dateutil==2.5.3
python-dwca-reader==0.9.2
python-igraph==0.7.1.post6
pytz==2016.7
PyYAML==3.11
pyzmq==15.1.0
qtconsole==4.1.1
redis==2.10.5
requests==2.9.1
requests-file==1.4.1
scikit-image==0.12.3
scikit-learn==0.18
scipy==0.17.0
Shapely==1.5.13
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
statsmodels==0.6.1
sympy==1.0
tensorflow==1.3.0
tensorflow-tensorboard==0.1.5
terminado==0.5
toolz==0.8.0
tornado==4.3
traitlets==4.3.1
update==0.4.4
wcwidth==0.1.7
Werkzeug==0.12.2
